# Generated by Django 3.0.7 on 2020-06-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
